# Start server: `docker-compose -d up`
# Stop  server: `docker-compose down`
version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - rethinkdb
  rethinkdb:
    #build: /rethinkdb
    image: rethinkdb
    ports:
     - "28015"
    #volumes:
     #- /data:/data
    #command: rethinkdb --bind all --data /data 
